included:
  - Sources
  - Tests
excluded:
  - Tests/LinuxMain.swift
  - Tests/*/XCTestManifests.swift
disabled_rules:
  - file_length
  - large_tuple
  - nesting
identifier_name:
  excluded:
    - x
    - y
    - id
    - a
    - b
