#if !canImport(ObjectiveC)
import XCTest

extension Day10Tests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Day10Tests = [
        ("test_part1_solution", test_part1_solution),
        ("test_part1_test", test_part1_test),
        ("test_part2_solution", test_part2_solution),
        ("test_part2_test", test_part2_test),
    ]
}

extension Day11Tests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Day11Tests = [
        ("test_part1_solution", test_part1_solution),
        ("test_part1_test", test_part1_test),
        ("test_part2_solution", test_part2_solution),
        ("test_part2_test", test_part2_test),
    ]
}

extension Day12Tests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Day12Tests = [
        ("test_part1_solution", test_part1_solution),
        ("test_part1_test", test_part1_test),
        ("test_part2_solution", test_part2_solution),
        ("test_part2_test", test_part2_test),
    ]
}

extension Day1Tests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Day1Tests = [
        ("test_part1_solution", test_part1_solution),
        ("test_part1_test", test_part1_test),
        ("test_part2_solution", test_part2_solution),
        ("test_part2_test", test_part2_test),
    ]
}

extension Day2Tests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Day2Tests = [
        ("test_part1_solution", test_part1_solution),
        ("test_part1_test", test_part1_test),
        ("test_part2_solution", test_part2_solution),
        ("test_part2_test", test_part2_test),
    ]
}

extension Day3Tests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Day3Tests = [
        ("test_part1_solution", test_part1_solution),
        ("test_part1_test", test_part1_test),
        ("test_part2_solution", test_part2_solution),
        ("test_part2_test", test_part2_test),
    ]
}

extension Day4Tests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Day4Tests = [
        ("test_part1_solution", test_part1_solution),
        ("test_part1_test", test_part1_test),
        ("test_part2_solution", test_part2_solution),
        ("test_part2_test", test_part2_test),
    ]
}

extension Day5Tests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Day5Tests = [
        ("test_part1_solution", test_part1_solution),
        ("test_part1_test", test_part1_test),
        ("test_part2_solution", test_part2_solution),
    ]
}

extension Day6Tests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Day6Tests = [
        ("test_part1_solution", test_part1_solution),
        ("test_part1_test", test_part1_test),
        ("test_part2_solution", test_part2_solution),
        ("test_part2_test", test_part2_test),
    ]
}

extension Day7Tests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Day7Tests = [
        ("test_part1_solution", test_part1_solution),
        ("test_part1_test", test_part1_test),
        ("test_part2_solution", test_part2_solution),
        ("test_part2_test", test_part2_test),
    ]
}

extension Day8Tests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Day8Tests = [
        ("test_part1_solution", test_part1_solution),
        ("test_part1_test", test_part1_test),
        ("test_part2_solution", test_part2_solution),
        ("test_part2_test", test_part2_test),
    ]
}

extension Day9Tests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Day9Tests = [
        ("test_part1_solution", test_part1_solution),
        ("test_part1_test", test_part1_test),
        ("test_part2_solution", test_part2_solution),
        ("test_part2_test", test_part2_test),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(Day10Tests.__allTests__Day10Tests),
        testCase(Day11Tests.__allTests__Day11Tests),
        testCase(Day12Tests.__allTests__Day12Tests),
        testCase(Day1Tests.__allTests__Day1Tests),
        testCase(Day2Tests.__allTests__Day2Tests),
        testCase(Day3Tests.__allTests__Day3Tests),
        testCase(Day4Tests.__allTests__Day4Tests),
        testCase(Day5Tests.__allTests__Day5Tests),
        testCase(Day6Tests.__allTests__Day6Tests),
        testCase(Day7Tests.__allTests__Day7Tests),
        testCase(Day8Tests.__allTests__Day8Tests),
        testCase(Day9Tests.__allTests__Day9Tests),
    ]
}
#endif
